### PR TITLE
fixes related to dog fooding

### PR DESCRIPTION
**Pull request by lachrist**
One large refactoring: 0b43e68334d180059a92c9f2339850f114ba9e67 and a bunch of fixes:
- 464aa35efcf51389da1f8f0978dd070c2be6e196 fixes https://github.com/getappmap/appmap-agent-js/issues/198
- a159356cd90d5e66bed239b53098d88ad6dd9bde fixes https://github.com/getappmap/appmap-agent-js/issues/208
- a64c375537397516a0f73ed76f72b2d4cf405531 fixes https://github.com/getappmap/appmap-agent-js/issues/209
- 85cc9cab68e61c870ce8d9ad4d27c4064a48ef8a fixes https://github.com/getappmap/appmap-agent-js/issues/217
- 831e6895678f8230558fd26c4c3e19c48e2f6f15 fixes https://github.com/getappmap/appmap-agent-js/issues/215
- 7fc1408d0ed60ad7197a59edc503c3a30968ff1c fixes https://github.com/getappmap/appmap-agent-js/issues/218
- 16c7703d1829e2835ea70eed304146ac7faef777 fixes https://github.com/getappmap/appmap-agent-js/issues/213
- b0f3f597ae16b4183fe3c038802ecc51d666addb fixes https://github.com/getappmap/appmap-agent-js/issues/221

### CODE REVIEW

**Comment by dustinbyrne** [comment]
What else is required here before this PR is considered done? I worry that the amount of changes here are already quite extensive with lots of refactors, fixes and features. Are these all linked to a single issue?

**Comment by dustinbyrne** [comment]
I'm not sure how to review this. Can this be split into separate pull requests?

**Comment by lachrist** [comment]
> I'm not sure how to review this. Can this be split into separate pull requests?
@dustinbyrne Each commit is independent and should build so they could potentially each be in their own PR. But doing the split and making sure that they can actually be released separately is going to be some work which I'm not sure I will be able to do before I come back.

**Comment by dustinbyrne** [comment]
The issue is that this is 8 issues across ~6500 lines of code in a single pull request. It becomes difficult to split up the responsibility of reviewing these fixes when everything resides within a single pull request.

**Comment by kgilpin** [comment]
Right - 1 PR per issue would be the expectation. If one PR depends on the
merge of a previous one, that's OK. GitHub will adjust the base branch of
the PR as the merges occur.

**Pull request merged**
